### PR TITLE
Added support for laravel 9 and php 8.1

### PR DESCRIPTION
**Pull request by stojankukrika**
Added support for laravel 9 and php 8.1 @asantibanez please merge

### CODE REVIEW

**Comment by baoanhng** [comment]
It doesn't seem to have conflicts with Laravel 9 @asantibanez

**Comment by fotrino** [comment]
@asantibanez could you merge this?

**Comment by luizpuretz** [comment]
@asantibanez please, merge!

**Comment by Hesesses** [comment]
@asantibanez we would also need this 🙏

**Pull request merged**
